import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { Toaster } from "sonner";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
        variables: { 
          colorPrimary: '#4f46e5',
          colorBackground: '#09090b',
          colorText: '#ffffff',
          colorTextSecondary: '#a1a1aa',
          colorInputText: '#ffffff',
          colorInputBackground: '#18181b',
        },
        elements: {
          card: 'border border-zinc-800 shadow-2xl bg-[#09090b]',
          headerTitle: 'text-white',
          headerSubtitle: 'text-zinc-400',
          socialButtonsBlockButton: 'text-white border-zinc-800 hover:bg-zinc-900',
          socialButtonsBlockButtonText: 'text-white font-medium',
          dividerLine: 'bg-zinc-800',
          dividerText: 'text-zinc-500',
          formFieldLabel: 'text-white',
          formFieldInput: 'bg-zinc-900 border-zinc-800 text-white',
          footerActionText: 'text-zinc-400',
          footerActionLink: 'text-indigo-400 hover:text-indigo-300',
          identityPreviewText: 'text-white bg-zinc-900 border border-zinc-800',
          formButtonPrimary: 'bg-indigo-600 hover:bg-indigo-500 text-white',
        }
      }}
    >
      <html
        lang="en"
        className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      >
        <body className="min-h-full flex flex-col">
          {children}
          <Toaster theme="dark" position="bottom-right" richColors />
        </body>
      </html>
    </ClerkProvider>
  );
}
